unleash:
  workers: 1
  test-cpu: 1
  timeout-coefficient: 5

mutants:
  arithmetic-base:
    enabled: true
  conditionals-boundary:
    enabled: true
  conditionals-negation:
    enabled: true
  increment-decrement:
    enabled: true
  invert-assignments:
    enabled: true
  invert-bitwise:
    enabled: true
  invert-bwassign:
    enabled: true
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: true
  invert-negatives:
    enabled: true
  remove-self-assignments:
    enabled: true
