{{- if include "spinoza.ownSecretNeeded" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spinoza.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spinoza.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.auth.existingSecret) .Values.auth.sessionSecret }}
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.sessionSecret | quote }}
  {{- end }}
  {{- if and (not .Values.auth.oidc.existingSecret) .Values.auth.oidc.clientSecret }}
  {{ .Values.auth.oidc.clientSecretKey }}: {{ .Values.auth.oidc.clientSecret | quote }}
  {{- end }}
  {{- if and (eq .Values.auth.mode "proxy") (not .Values.auth.proxy.existingSecret) .Values.auth.proxy.sharedSecret }}
  {{ .Values.auth.proxy.existingSecretKey }}: {{ .Values.auth.proxy.sharedSecret | quote }}
  {{- end }}
{{- end }}
